intro h,
cases h with hab hnba,
rw le_iff_exists_add at hab hnba ⊢,
cases hab with c hc,
induction c with d hd,
rw add_zero at hc,
exfalso,
apply hnba,
use 0,
rw hc,
rw add_zero,
refl,
rw add_succ at hc,
use d,
rw succ_add,
exact hc,