rw le_iff_exists_add at hab hba,
cases hba with d hd,
cases hab with e he,
rw he at hd,
rw add_assoc at hd,
symmetry at hd,
have h := eq_zero_of_add_right_eq_self hd,
have h1:= add_right_eq_zero h,
rw he,
rw h1,
rw add_zero,
refl,