rw two_eq_succ_one,
rw one_eq_succ_zero,
repeat {rw pow_succ},
repeat {rw pow_zero},
rw succ_eq_add_one,
rw succ_add 0 1,
rw zero_add 1,
rw succ_eq_add_one,
repeat {rw add_mul},
repeat {rw one_mul},
repeat {rw add_mul},
repeat {rw mul_add},
simp,